### ISSUE TITLE
Add brain regions

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-schema-models#31]
Add the CCF brain regions.

https://api.brain-map.org/api/v2/data/Structure/query.json?criteria=[graph_id$eq1][hemisphere_id$eq3]&num_rows=all

data model is:

name <-- name
abbreviation <-- acronym
color <-- "#" + color_hex_triplet
hemisphere <-- 1 = "left", 2="right", 3="both"
id <-- id
parent_id <-- parent_structure_id
order <-- graph_order

**Comment by saskiad** [comment]
do we need all of this? If we treat the ABA as a Registry, we should be able to use the name, abbreviation, id and not need the other items.

**Comment by dbirman** [comment]
Whoops this is now a duplicate of https://github.com/AllenNeuralDynamics/aind-data-schema-models/issues/52
