### ISSUE TITLE
Alphabetical order is inconsistent

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema-models#32]
**Describe the bug**
Use the model name to alphabetize models in both the model and enum lists.

**To Reproduce**
example: IMEC. In the models it's ordered by "Interuniversity..." and in the enum it's order be "IMEC"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dyf** [comment]
resolved by #35
