### ISSUE TITLE
Add model for muscles

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema-models#37]
@lambdaloop will provide list

**Comment by saskiad** [comment]
spinodeltoidus, pectoralis major, triceps brachii, biceps brachii, deltoideus,
extensor carpi radialis longus, extensor digitorum communis, extensor
digitorum lateralis, extensor carpi ulnaris, flexor carpi radialis, flexor
digitorum profundus, and flexor carpi ulnaris.

**Comment by saskiad** [comment]
I would like to try to link these muscles to the mouse anatomy ontology if possible.

**Comment by lambdaloop** [comment]
I searched a bit and I think all of the above have a corresponding EMAPS id.
https://www.informatics.jax.org/vocab/gxd/anatomy/EMAPS:3557828

I think we could fully specify the muscle by name, EMAPS id, and body side (left or right)

**Comment by saskiad** [comment]
that is a developmental atlas. Any change you see them in the adult atlas?
https://www.informatics.jax.org/vocab/gxd/ma_ontology

**Comment by saskiad** [comment]
and yes, we'd use name, id (with registry information), and side.

**Comment by lambdaloop** [comment]
It seems like all of the ones above (except spinodeltoidus, which would be under deltoid) are available in the anatomy you linked: https://www.informatics.jax.org/vocab/gxd/ma_ontology/MA:0002888

From comparing the two, I think the two atlases are quite similar, although the developmental atlas seems more detailed. I like how the developmental atlas breaks down the biceps and triceps muscles into different heads, which we know have distinct motor unit activity. 

The developmental atlas also has a better and more consistent hierarchy. For instance, the subentries for "forelimb muscle" in mouse atlas don't actually point to the forelimb muscles that are elsewhere in the hierarchy: https://www.informatics.jax.org/vocab/gxd/ma_ontology/MA:0000615 

That said, I think the mouse adult atlas is still rather comprehensive and if it makes more sense within the greater Allen institute metadata then it should be enough with an additional notes or submuscle field to specify muscles more precisely.

**Comment by saskiad** [comment]
then let's use the developmental atlas if it's more comprehensive. Thanks!

**Comment by saskiad** [comment]
This tool might help us convert ontology into csv:
https://pnnl-comp-mass-spec.github.io/OBO-Data-Converter/

**Comment by saskiad** [comment]
And this is the ontology we're using:
https://obofoundry.org/ontology/emapa.html

**Comment by dbirman** [comment]
Couldn't get that exe working so I just did the most basic thing and dumped the ontology text file to CSV. I think we can strip the "EMAPA" prefix and move those into the headers. And the part_of prefixes can be changed to parent/child relationships, except that some children appear to have multiple direct parents? I'm not sure how that works.

The other caveat here is that this is ~8000 structures that are all marked as "anatomical_structure" so from a usability standpoint it's not convenient. The examples you listed earlier are almost all children of 35778 (skeletal musculature) so I guess if there's some UI that lets users pick a parent structure and then filters for descendants that would make it a bit more usable.

[ontology.csv](https://github.com/user-attachments/files/16500983/ontology.csv)

**Comment by dbirman** [comment]
Cleaned up version

[ontology.csv](https://github.com/user-attachments/files/16501194/ontology.csv)

**Comment by dbirman** [comment]
@lambdaloop or @saskiad can one of you please confirm what **spinodeltoidus** and **deltoideus** are in this ontology (CSV attached just above). I can't find them in the "name" column. All of the other muscles are there.

**Comment by lambdaloop** [comment]
@dbirman 
Thank you for taking this on!

I think the JAX anatomy browser works well to find ids: https://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:35578

deltoideus corresponds to "deltoid", EMAPA:18177

spinodeltoidus corresponds to "pars scapularis of deltoid", EMAPA:36163
(it's marked a synonym in the JAX browser: https://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:36163 )
