### ISSUE TITLE
Verify semantic versions are incremented properly

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-schema-models#70]
**Describe the bug**
In theory, the semantic versions should parse the commit message and increment appropriately

**To Reproduce**
1. Merge a PR with the words "BREAKING CHANGE" or "feat" in the commit message
2. Check if the major/minor versions are incremented

**Expected behavior**
When a user merges a PR with the phrase `BREAKING CHANGE`, then the major version number should increment.
When a user merges a PR with the phrase `feat`, then the minor version number should increment.
Documentation exists for how to do this, either in readthedocs or another markdown file somewhere.

**Additional context**
This might be working and may be a matter of checking the commit messages when merging into main

**Comment by dbirman** [comment]
I just merged a branch with "feat: "in the squashed commit and it bumped the minor version. Normal PRs without feat: seem to bump the patch version. So this does seem to be working (pending someone merging a breaking change to see if it bumps major version)

**Comment by jtyoung84** [comment]
I'm going to go ahead and close this out
