### ISSUE TITLE
Add the MGI alleles as a csv

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-data-schema-models#89]
**Is your feature request related to a problem? Please describe.**
We want to have the MGI allele IDs in the subject metadata

**Describe the solution you'd like**
there is a rpt file here: https://www.informatics.jax.org/downloads/reports/MGI_PhenotypicAllele.rpt
convert this to a csv, add it to the repo, and construct the allele class

**Describe alternatives you've considered**

**Additional context**

**Comment by dbirman** [comment]
Updating this request with what we think the current requirements are, @saskiad can weigh in:

Is your feature request related to a problem? Please describe.
Need to add MGI alleles as a model that we can validate against

Describe the solution you'd like
there is a rpt file here: https://www.informatics.jax.org/downloads/reports/MGI_PhenotypicAllele.rpt
construct an Allele class that validates against this external resource

**Comment by jtyoung84** [comment]
Duplicated
