### ISSUE TITLE
sigma aldritch not showing up in orgs list

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-schema-models#90]
Sigma Aldritch lacks an abbreviation, and is this not recieving a mapping in Organizations.

**Comment by saskiad** [comment]
it's unclear to me what the issue is here. Sigma-Aldrich (note the name is spelled wrong in the schema, so that should be fixed) is entered the same way as the others. What's the problem that's happening?

**Comment by saskiad** [comment]
- [ ] Fix spelling: "Sigma-Aldrich"
